# Generated by Django 3.2.6 on 2021-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_super_user',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
